---
title: "Books-2017"
description: |
  A short description of the post.
author:
  - name: Roy Emanuel
    url: {}
date: 02-07-2021
output:
  distill::distill_article:
    self_contained: false
draft: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

These are the books that I read during about half of 2017. I'll try to
note anything I really liked or didn't from them.



The Handmaid's Tale, Margaret Atwood

Ready Player One, Ernest Cline

A Knight for All Kingdoms, George R. R. Martin

The Choose Yourself Guide to Wealth, James Altucher

**Man's Search For Meaning, Victor Frankl**

This is a book I recommend to every adult.

Mastery, 

Snow Crash, 

Sand, Hugh Howey

Wool, Hugh Howey

**The Colour of Magic, Terry Pratchett**

My start with Discworld. An amazing series that brings me joy with
every book. Sir Pratchett earned his knighthood, plus some.

The One Thing

**Mr. Norrel and Jonathan Strange, ** 

I really enjoyed this book even though I knew it was boring as I read
it. 

**Stardust, Neil Gaiman**

Much like Sir Pratchett, this was my introduction to Neil Gaiman. His
writing makes my heart ache. I want to tell a story to someone that
makes them feel like this.

Norse Mythology, Neil Gaiman

how to Write a Lot, Paul Silvia

Neuromancer

The
